package main

import (
	"crypto/tls"
	"log"
	"net/http"
	"strings"
	"sync"

	"github.com/elazarl/goproxy"
)

// BypassSet holds domains that should skip MITM interception.
type BypassSet struct {
	exact    map[string]bool // exact domain matches
	wildcard []string        // wildcard patterns like "*.apple.com"
}

// NewBypassSet creates a BypassSet from a list of domain strings.
// Entries starting with "*." are treated as wildcard patterns.
// All other entries are exact matches.
func NewBypassSet(domains []string) *BypassSet {
	bs := &BypassSet{exact: make(map[string]bool)}
	for _, d := range domains {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		if strings.HasPrefix(d, "*.") {
			bs.wildcard = append(bs.wildcard, strings.TrimPrefix(d, "*"))
		} else {
			bs.exact[d] = true
		}
	}
	return bs
}

// Contains returns true if the hostname matches an exact or wildcard entry.
func (bs *BypassSet) Contains(hostname string) bool {
	if bs.exact[hostname] {
		return true
	}
	for _, suffix := range bs.wildcard {
		if strings.HasSuffix(hostname, suffix) {
			return true
		}
	}
	return false
}

// stripPort removes the port from a host:port string.
func stripPort(host string) string {
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		return host[:idx]
	}
	return host
}

// memCertStore implements goproxy.CertStorage for in-memory leaf certificate
// caching per D-13. On-the-fly leaf certificates generated by goproxy's MITM
// are cached here with LRU eviction to avoid regenerating certs for frequently
// visited domains.
//
// goproxy.CertStorage interface:
//
//	Fetch(hostname string, gen func() (*tls.Certificate, error)) (*tls.Certificate, error)
//
// On cache miss, gen() is called to create the cert, which is then cached.
type memCertStore struct {
	mu      sync.RWMutex
	cache   map[string]*tls.Certificate
	maxSize int      // LRU eviction threshold
	order   []string // insertion order for LRU eviction
}

// newMemCertStore creates a memCertStore with the given max cache size.
func newMemCertStore(maxSize int) *memCertStore {
	return &memCertStore{
		cache:   make(map[string]*tls.Certificate),
		maxSize: maxSize,
	}
}

// Fetch retrieves a cached leaf certificate for the given hostname.
// On cache miss, calls gen() to generate a new cert, caches it, and returns it.
// Evicts the oldest entry when cache exceeds maxSize (LRU).
func (s *memCertStore) Fetch(host string, gen func() (*tls.Certificate, error)) (*tls.Certificate, error) {
	s.mu.RLock()
	cert, ok := s.cache[host]
	s.mu.RUnlock()
	if ok {
		return cert, nil
	}

	// Cache miss: generate new cert.
	cert, err := gen()
	if err != nil {
		return nil, err
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	// LRU eviction: if at capacity, remove oldest entry
	if len(s.cache) >= s.maxSize {
		if len(s.order) > 0 {
			oldest := s.order[0]
			s.order = s.order[1:]
			delete(s.cache, oldest)
		}
	}
	s.cache[host] = cert
	s.order = append(s.order, host)
	return cert, nil
}

// SetupProxy configures the goproxy proxy server with:
// - In-memory CertStore for on-the-fly leaf cert caching (D-13)
// - Conditional MITM: bypass domains get ConnectAccept, others get ConnectMitm (D-06, D-09)
// - Response handler chain: Content-Type routing to transcoder/minifier (D-07, D-08)
// Returns the configured *goproxy.ProxyHttpServer.
func SetupProxy(caCert *tls.Certificate, bypassSet *BypassSet, chain *HandlerChain, verbose bool) *goproxy.ProxyHttpServer {
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = verbose

	// Per D-13: on-the-fly leaf certificate generation with LRU-cached CertStore.
	// goproxy uses this to cache generated leaf certs per domain, avoiding
	// repeated certificate generation for frequently visited sites.
	// 1024 entries covers typical browsing session with ample headroom.
	proxy.CertStore = newMemCertStore(1024)

	// Conditional MITM per D-09
	proxy.OnRequest().HandleConnectFunc(
		func(host string, ctx *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
			hostname := stripPort(host)
			if bypassSet.Contains(hostname) {
				if verbose {
					log.Printf("BYPASS: %s (cert-pinned/bypass list)", hostname)
				}
				return &goproxy.ConnectAction{Action: goproxy.ConnectAccept}, host
			}
			return &goproxy.ConnectAction{
				Action:    goproxy.ConnectMitm,
				TLSConfig: goproxy.TLSConfigFromCA(caCert),
			}, host
		})

	// Response transformation pipeline per D-07
	proxy.OnResponse().DoFunc(
		func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
			return chain.HandleResponse(resp)
		})

	return proxy
}
