package main

import (
	"crypto/tls"
	"encoding/json"
	"log"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/elazarl/goproxy"
)

// hardcodedBypassDomains contains domains that must NEVER be MITM-intercepted,
// regardless of user configuration. Per D-14: banking, auth, gov, health, and
// payment domains are hardcoded to prevent breaking cert-pinned apps.
// These cannot be removed by user config -- only extended.
var hardcodedBypassDomains = []string{
	// Banking & Financial
	"*.chase.com", "*.bankofamerica.com", "*.wellsfargo.com",
	"*.capitalone.com", "*.citi.com", "*.schwab.com",
	"*.fidelity.com", "*.vanguard.com", "*.usaa.com",
	// Authentication & Identity
	"*.apple.com", "accounts.google.com", "login.microsoftonline.com",
	"*.okta.com", "*.auth0.com", "*.duosecurity.com",
	// Payments
	"*.paypal.com", "*.venmo.com", "*.stripe.com", "*.square.com",
	// Government
	"*.gov", "*.mil",
	// Health
	"*.epic.com", "*.mychart.com",
	// Aviation (belt-and-suspenders with DNS bypass)
	"*.foreflight.com", "*.garmin.com", "*.faa.gov",
}

// BuildBypassSet creates a BypassSet that merges hardcoded never-MITM domains
// with user-defined domains from a YAML config file. Hardcoded domains cannot
// be removed by user config. If the user file is missing or invalid, only
// hardcoded domains are used (graceful degradation).
func BuildBypassSet(userBypassPath string) (*BypassSet, error) {
	// Start with a copy of hardcoded domains (never modify original).
	allDomains := make([]string, len(hardcodedBypassDomains))
	copy(allDomains, hardcodedBypassDomains)

	// Try loading user-defined domains. Graceful degradation on error.
	userDomains, err := LoadBypassDomains(userBypassPath)
	if err == nil {
		allDomains = append(allDomains, userDomains...)
	} else {
		log.Printf("WARN: Failed to load user bypass domains from %s: %v (using hardcoded only)", userBypassPath, err)
	}

	return NewBypassSet(allDomains), nil
}

// BypassSet holds domains that should skip MITM interception.
type BypassSet struct {
	exact    map[string]bool // exact domain matches
	wildcard []string        // wildcard patterns like "*.apple.com"
}

// NewBypassSet creates a BypassSet from a list of domain strings.
// Entries starting with "*." are treated as wildcard patterns.
// All other entries are exact matches.
func NewBypassSet(domains []string) *BypassSet {
	bs := &BypassSet{exact: make(map[string]bool)}
	for _, d := range domains {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		if strings.HasPrefix(d, "*.") {
			bs.wildcard = append(bs.wildcard, strings.TrimPrefix(d, "*"))
		} else {
			bs.exact[d] = true
		}
	}
	return bs
}

// Contains returns true if the hostname matches an exact or wildcard entry.
func (bs *BypassSet) Contains(hostname string) bool {
	if bs.exact[hostname] {
		return true
	}
	for _, suffix := range bs.wildcard {
		if strings.HasSuffix(hostname, suffix) {
			return true
		}
	}
	return false
}

// stripPort removes the port from a host:port string.
func stripPort(host string) string {
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		return host[:idx]
	}
	return host
}

// memCertStore implements goproxy.CertStorage for in-memory leaf certificate
// caching per D-13. On-the-fly leaf certificates generated by goproxy's MITM
// are cached here with LRU eviction to avoid regenerating certs for frequently
// visited domains.
//
// goproxy.CertStorage interface:
//
//	Fetch(hostname string, gen func() (*tls.Certificate, error)) (*tls.Certificate, error)
//
// On cache miss, gen() is called to create the cert, which is then cached.
type memCertStore struct {
	mu      sync.RWMutex
	cache   map[string]*tls.Certificate
	maxSize int      // LRU eviction threshold
	order   []string // insertion order for LRU eviction
}

// newMemCertStore creates a memCertStore with the given max cache size.
func newMemCertStore(maxSize int) *memCertStore {
	return &memCertStore{
		cache:   make(map[string]*tls.Certificate),
		maxSize: maxSize,
	}
}

// Fetch retrieves a cached leaf certificate for the given hostname.
// On cache miss, calls gen() to generate a new cert, caches it, and returns it.
// Evicts the oldest entry when cache exceeds maxSize (LRU).
func (s *memCertStore) Fetch(host string, gen func() (*tls.Certificate, error)) (*tls.Certificate, error) {
	s.mu.RLock()
	cert, ok := s.cache[host]
	s.mu.RUnlock()
	if ok {
		return cert, nil
	}

	// Cache miss: generate new cert.
	cert, err := gen()
	if err != nil {
		return nil, err
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	// LRU eviction: if at capacity, remove oldest entry
	if len(s.cache) >= s.maxSize {
		if len(s.order) > 0 {
			oldest := s.order[0]
			s.order = s.order[1:]
			delete(s.cache, oldest)
		}
	}
	s.cache[host] = cert
	s.order = append(s.order, host)
	return cert, nil
}

// MaxSavingsIPSet tracks which client source IPs are in "Max Savings" mode.
// The proxy polls the Pi's dashboard daemon /api/mode/ips endpoint to populate this set.
// IPs in this set get ConnectMitm (HTTPS interception with intermediate CA).
// IPs NOT in this set get ConnectAccept (TCP passthrough, no MITM).
type MaxSavingsIPSet struct {
	mu      sync.RWMutex
	ips     map[string]bool
	apiURL  string // e.g., "http://10.13.13.2:80"
	enabled bool   // false when apiURL is empty (pre-Phase 5 mode)
}

// NewMaxSavingsIPSet creates a new IP set. If apiURL is empty, the set is disabled
// and Contains() always returns true (MITM all non-bypass traffic, pre-Phase 5 behavior).
func NewMaxSavingsIPSet(apiURL string) *MaxSavingsIPSet {
	return &MaxSavingsIPSet{
		ips:     make(map[string]bool),
		apiURL:  apiURL,
		enabled: apiURL != "",
	}
}

// Contains returns true if the IP should receive MITM treatment.
// When the set is disabled (no apiURL), returns true for all IPs (backward-compatible).
func (s *MaxSavingsIPSet) Contains(ip string) bool {
	if !s.enabled {
		return true // Pre-Phase 5: MITM everything
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.ips[ip]
}

// Update replaces the IP set with a new list of IPs.
func (s *MaxSavingsIPSet) Update(ips []string) {
	newSet := make(map[string]bool, len(ips))
	for _, ip := range ips {
		newSet[ip] = true
	}
	s.mu.Lock()
	s.ips = newSet
	s.mu.Unlock()
}

// StartPolling begins periodic polling of the dashboard API.
// Runs in a loop until stopped. Logs warnings on fetch errors
// but continues with the last known set (graceful degradation per Pitfall 6).
func (s *MaxSavingsIPSet) StartPolling(interval time.Duration) {
	if !s.enabled {
		return
	}
	client := &http.Client{Timeout: 5 * time.Second}
	url := strings.TrimRight(s.apiURL, "/") + "/api/mode/ips"
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	// Fetch immediately on start, then on each tick
	s.fetchAndUpdate(client, url)
	for range ticker.C {
		s.fetchAndUpdate(client, url)
	}
}

// fetchAndUpdate fetches the current Max Savings IPs from the dashboard API.
func (s *MaxSavingsIPSet) fetchAndUpdate(client *http.Client, url string) {
	resp, err := client.Get(url)
	if err != nil {
		log.Printf("WARN: failed to fetch Max Savings IPs from %s: %v (using last known set)", url, err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Printf("WARN: dashboard API returned %d for %s (using last known set)", resp.StatusCode, url)
		return
	}
	var result struct {
		MaxSavingsIPs []string `json:"maxsavings_ips"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		log.Printf("WARN: failed to decode Max Savings IPs response: %v (using last known set)", err)
		return
	}
	s.Update(result.MaxSavingsIPs)
}

// extractSourceIP extracts the client IP from the CONNECT request.
// The source IP is preserved through the WireGuard tunnel from the Pi's subnet.
func extractSourceIP(req *http.Request) string {
	if req == nil {
		return ""
	}
	host := req.RemoteAddr
	// RemoteAddr is typically "IP:port"
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		return host[:idx]
	}
	return host
}

// SetupProxy configures the goproxy proxy server with:
// - In-memory CertStore for on-the-fly leaf cert caching (D-13)
// - Conditional MITM: bypass domains get ConnectAccept, others get ConnectMitm (D-06, D-09)
// - Response handler chain: Content-Type routing to transcoder/minifier (D-07, D-08)
// Returns the configured *goproxy.ProxyHttpServer.
func SetupProxy(caCert *tls.Certificate, bypassSet *BypassSet, maxSavingsIPs *MaxSavingsIPSet, chain *HandlerChain, verbose bool) *goproxy.ProxyHttpServer {
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = verbose

	// Per D-13: on-the-fly leaf certificate generation with LRU-cached CertStore.
	// goproxy uses this to cache generated leaf certs per domain, avoiding
	// repeated certificate generation for frequently visited sites.
	// 1024 entries covers typical browsing session with ample headroom.
	proxy.CertStore = newMemCertStore(1024)

	// Conditional MITM per D-09, with per-device mode awareness (Phase 5)
	proxy.OnRequest().HandleConnectFunc(
		func(host string, ctx *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
			hostname := stripPort(host)

			// Always bypass cert-pinned domains (D-14)
			if bypassSet.Contains(hostname) {
				if verbose {
					log.Printf("BYPASS: %s (cert-pinned/bypass list)", hostname)
				}
				return &goproxy.ConnectAction{Action: goproxy.ConnectAccept}, host
			}

			// Check if source device is in Max Savings mode (per Research Pattern 3, Pitfall 5)
			sourceIP := extractSourceIP(ctx.Req)
			if !maxSavingsIPs.Contains(sourceIP) {
				// Quick Connect device: TCP passthrough, no MITM
				if verbose {
					log.Printf("PASSTHROUGH: %s from %s (Quick Connect mode)", hostname, sourceIP)
				}
				return &goproxy.ConnectAction{Action: goproxy.ConnectAccept}, host
			}

			// Max Savings device: MITM with intermediate CA
			if verbose {
				log.Printf("MITM: %s from %s (Max Savings mode)", hostname, sourceIP)
			}
			return &goproxy.ConnectAction{
				Action:    goproxy.ConnectMitm,
				TLSConfig: goproxy.TLSConfigFromCA(caCert),
			}, host
		})

	// Response transformation pipeline per D-07
	proxy.OnResponse().DoFunc(
		func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
			return chain.HandleResponse(resp)
		})

	return proxy
}
