---
- name: Restart skygate-autorate
  ansible.builtin.systemd:
    name: skygate-autorate
    state: restarted
    daemon_reload: true
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
