---
# Networking role handlers

- name: Restart networkmanager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Restart hostapd
  ansible.builtin.systemd:
    name: hostapd
    state: restarted

- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
